using System.ComponentModel.DataAnnotations;

namespace ChatHaven.Models
{
    public class Request
    {
        [Required]
        [Key] // Primary
        public int request_id { get; set; } // generated by database

        [Required]
        public required int requester_id { get; set; }

        [Required]
        public required int channel_owner_id { get; set; }

        [Required]
        public required int channel_id { get; set; }

        [Required]
        public required string requester_name { get; set; }

        [Required]
        public required string channel_name { get; set; }

        [Required]
        public required string team_name { get; set; }

        [Required]
        public required DateTime created_at { get; set; }
    }
}