using System.ComponentModel.DataAnnotations;

namespace ChatHaven.Models
{
    public class Story
    {
        [Required]
        [Key] // Primary
        public int story_id { get; set; } // generated by database

        [Required]
        public required int user_id { get; set; }

        [Required]
        public required string username { get; set; }

        [Required]
        public required string file_type { get; set; }

        [Required]
        public required string url { get; set; }

        [Required]
        public required DateTime created_at { get; set; }
    }
}